data class BetDetail(
    val betLevel:String?=null,
    val betStarts:Int,
    val betStatusName:String?=null,
    val betTypeName:String?=null,
    val bgSrc:String?=null,
    val cashOutOdds:String?=null,
    val totalOdds:String?=null,
    val totalStake:String?=null,
    val totalWin:String?=null,
    val cashOutValue:String?=null,
    val createdDate:String?=null,
    val betSelections:List<BetSelection>? = null,
    val betStatus:Int,
    val betType:Int,
    val betId:Number
)

data class BetSelection(
    val selectionId:Int?=null,
    val selectionStatus:Int?=null,
    val price:String?=null,
    val name:String?=null,
    val spec:String?=null,
    val marketTypeId:Int?=null,
    val marketId:Int?=null,
    val marketName:String?=null,
    val isLive:Boolean,
    val isBetBuilder:Boolean,
    val isBanker:Boolean,
    val isVirtual:Boolean,
    val eventId:Int?=null,
    val feedEventId:Int?=null,
    val eventName:String?=null,
    val sportTypeId:Int?=null,
    val categoryId:Int?=null,
    val champId:Int?=null,
    val eventDate:String?=null,
    val rC:Boolean,
    val isLiveOrVirtual:Boolean,
    val earlyPayout:Boolean,
    val boreDraw:Boolean,
    val dbId:Int?=null,
    val eventScore:String?=null
)